social_group_invite.settings:
  type: config_object
  label: 'Social Group Invite Settings'
  mapping:
    invite_helper:
      type: text
      label: 'The invite helper text.'
    email_verification:
      type: boolean
      label: 'Allow invited user to skip email verification.'
