core.entity_view_display.post.photo.featured:
  expected_config:
    content:
      field_post:
        settings:
          trim_length: 400
        type: text_trimmed
    hidden:
      like_and_dislike: true
  update_actions:
    delete:
      hidden:
        like_and_dislike: true
    change:
      content:
        field_post:
          settings:
            more_class: more-link
            more_link: true
            more_text: more
            summary_handler: full
            trim_length: 250
            trim_options:
              text: false
              trim_zero: false
            trim_suffix: ...
            trim_type: chars
            wrap_class: trimmed
            wrap_output: false
          type: smart_trim
