services:
  php:
    image: q0rban/tugboat-drupal:8.9
    default: true
    depends:
      - mysql
    commands:
      update: |
        set -eux
        # Check out a branch using the unique Tugboat ID for this repository, to
        # ensure we don't clobber an existing branch.
        git checkout -b $TUGBOAT_REPO_ID
        # This is an environment variable we added in the Dockerfile that
        # provides the path to Drupal composer root (not the web root).
        cd $DRUPAL_COMPOSER_ROOT
        rm composer.*
        rm -rf web
        wget https://raw.githubusercontent.com/goalgorilla/social_template/master/composer.json
        wget https://raw.githubusercontent.com/goalgorilla/social_template/master/composer.lock
        # We configure the Drupal project to use the checkout of the module as a
        # Composer package repository.
        composer config repositories.tugboat vcs $TUGBOAT_ROOT
        # Now we can require this theme, specifing the branch name we created
        # above that uses the $TUGBOAT_REPO_ID environment variable.
        composer require goalgorilla/open_social:dev-$TUGBOAT_REPO_ID drush/drush

        # Install Drupal on the site.
        vendor/bin/drush \
          --yes \
          --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat \
          --site-name="Open Social" \
          --account-pass=${ADMIN_PASSWORD} \
          site:install social

        # Set up the files directory permissions.
        mkdir -p /var/www/drupal/html/sites/default/files
        chgrp -R www-data /var/www/drupal/html/sites/default/files
        chmod 2775 /var/www/drupal/html/sites/default/files
        chmod -R g+w /var/www/drupal/html/sites/default/files
        ln -snf /var/www/drupal/html $DOCROOT

      build: |
        set -eux
        # Delete and re-check out this branch in case this is built from a Base Preview.
        git branch -D $TUGBOAT_REPO_ID || true
        git checkout -b $TUGBOAT_REPO_ID || true
        cd $DRUPAL_COMPOSER_ROOT
        composer install --optimize-autoloader
        # Update this module, including all dependencies.
        composer update drupal/open_social --with-all-dependencies
        vendor/bin/drush --yes updb
        vendor/bin/drush cache:rebuild

  mysql:
    image: tugboatqa/mysql:5

